/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CustomerIdImport } from './routes/$customerId'
import { Route as IndexImport } from './routes/index'
import { Route as OrderIndexImport } from './routes/order/index'

// Create/Update Routes

const CustomerIdRoute = CustomerIdImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OrderIndexRoute = OrderIndexImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$customerId': {
      id: '/$customerId'
      path: '/$customerId'
      fullPath: '/$customerId'
      preLoaderRoute: typeof CustomerIdImport
      parentRoute: typeof rootRoute
    }
    '/order/': {
      id: '/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$customerId': typeof CustomerIdRoute
  '/order': typeof OrderIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$customerId': typeof CustomerIdRoute
  '/order': typeof OrderIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$customerId': typeof CustomerIdRoute
  '/order/': typeof OrderIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$customerId' | '/order'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$customerId' | '/order'
  id: '__root__' | '/' | '/$customerId' | '/order/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerIdRoute: typeof CustomerIdRoute
  OrderIndexRoute: typeof OrderIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerIdRoute: CustomerIdRoute,
  OrderIndexRoute: OrderIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$customerId",
        "/order/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$customerId": {
      "filePath": "$customerId.tsx"
    },
    "/order/": {
      "filePath": "order/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
